### PR TITLE
rosparam for ip of bridge and netpus + more conversions + compilation fix on jetson

### PR DESCRIPTION
**Pull request by NiklasRolleberg**
The ip address of the bridge node and the computer can now be set with rosparam. It is no longer necessary to run the bridge on the same computer as Neptus.

The node now compiles and runs fine on the jetson.

note: Estimated state converter no longer converts std::msgs point to EstimatedState, now it converts "imc_ros_bridge::EstimatedState" to imc::EstimatedState

### CODE REVIEW

**Comment by ignaciotb** [comment]
@NiklasRolleberg I'd like to test this on SAM on Friday/Monday before I merge it

**Comment by KKalem** [comment]
> @NiklasRolleberg I'd like to test this on SAM on Friday/Monday before I merge it

The BT also needs to be updated to use the new EstimatedState message. See gitter.

**Review by Jollerprutt — COMMENTED** [review]
Looks good, has this been tested on a Xavier?

**Comment by NiklasRolleberg** [comment]
Nope not yet

**Comment by nilsbore** [comment]
i don't know what the status on this is (cc @KKalem) but we should make sure to get this PR merged ASAP to facilitate further collaboration. Good work @NiklasRolleberg !

**Comment by KKalem** [comment]
Can be merged (@nilsbore). There will be some changes in the BT and stonefish_sim mission.launch to accommodate the changes here.

**Review by KKalem — APPROVED** [review]

**Pull request merged**
